<?php
$collection = $this->mongo->Users;
$datanew = $collection->findOne(['uid' => $_COOKIE['login']]);
if ($datanew->role == "user") {
    echo "<h3>NOT A ADMIN </h3>";
    die;
}

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>app: Homepage</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
     rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;1,600&display=swap"
     rel="stylesheet">
    <link rel="stylesheet" href="../../../public/assets/css/stylee.css">

</head>
<!-- admin panel -->

<body>
    <nav class="navbar">
        <img src="../../../public/assets/images/logo-res.png" class="logo" alt="" width="50px">
        <ul class="links-container">
            <li class="link-item"><a href="/login/logout" class="link">Logout</a></li>
            <li class="link-item"><a href="/index/home" class="link">Home</a></li>
            <li class="link-item"><a href="" class="link">Admin</a></li>
        </ul>
    </nav>

    <hr>
    <h1 class="text-center">Add Restaurants in this app</h1>
    <form action="/admin/addresturant" method="POST">
  <div class="form-group">
    <label for="exampleInputEmail1">Rid</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="rid" placeholder="Enter id">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Restaurant Name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="rname"  placeholder="Enter restaurant name">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Restaurant cuisine</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="cuisine"  placeholder="Enter cuisine">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Restaurant address</label>
    <input type="text" class="form-control"  name="raddress" placeholder="Enter restaurant address">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Restaurant Manager details</label>
    <input type="text" class="form-control"  name="rmanager" placeholder="Enter restaurant manager details">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">REstaurant details image</label>
    <input type="text" class="form-control"  name="img" placeholder="Enter image url">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Restaurant ratings</label>
    <input type="text" class="form-control"  name="ratings" placeholder="Enter restaurant ratings score">
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

    <hr>
    <h1 class="text-center">All Restaurants</h1>

    <table class="table text-center" id='details'>
        <thead class="text-center   ">
            <tr>
                <th>ID</th>
                <th>NAME</th>
                <th>CUISINE</th>
                <th>ADDRESS</th>
                <th>MANAGER-DETAILS</th>
                <th>RATINGS</th>
                <th>ACTION</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $collection = $this->mongo->resturant;
            $data = $collection->find();


            foreach ($data as $value) {

                echo "<tr><td>" . $value->rid . "</td>";
                echo "<td>" . $value->rname . "</td>";
                echo "<td>" . $value->cuisine . "</td>";
                echo "<td>" . $value->raddress . "</td>";
                echo "<td>" . $value->rmanager . "</td>";
                echo "<td>" . $value->ratings . "</td>";
                echo "<td><a href='/admin/editrestraunt?id=$value->rid' class='btn btn-info'>Edit</a>
                <a href='/admin/deleterestraunt?id=$value->rid' class='btn btn-danger'>Delete</a></td></tr>";
            }


            ?>
        </tbody>
    </table>
    </div>

    <hr>
    <h1 class="text-center">All Users</h1>
    <table class="table text-center" id='details'>
        <thead class="text-center   ">
            <tr>
                <th>ID</th>
                <th>NAME</th>
                <th>EMAIL</th>
                <th>ROLE-DETAILS</th>
            </tr>
        </thead>
        <tbody>
        <tbody>
            <?php
          $collection = $this->mongo->Users;
          $data = $collection->find();

            foreach ($data as $value) {

                echo "<tr><td>" . $value->uid . "</td>";
                echo "<td>" . $value->name . "</td>";
                echo "<td>" . $value->email . "</td>";
                echo "<td>" . $value->role . "</td></tr>";
            }


            ?>
        </tbody>
    </table>
    </div>

    <hr>
    <h1 class="text-center">All Review</h1>
    <table class="table text-center" id='details'>
        <thead class="text-center   ">
            <tr>
                <th>ID</th>
                <th>NAME</th>
                <th>REVIEW</th>
               
            </tr>
        </thead>
        <tbody>
        <tbody>
            <?php
          $collection = $this->mongo->review;
          $data = $collection->find();

            foreach ($data as $value) {

             
                echo "<tr><td>" . $value->uid . "</td>";
                echo "<td>" . $value->name . "</td>";
                echo "<td>" . $value->review . "</td></tr>";
            }


            ?>
        </tbody>
    </table>
    </div>
   
</body>
<script src="./jS/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
 integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
 integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>

</html>