<?php
$collection = $this->mongo->Users;
$datanew = $collection->findOne(['uid' => $_COOKIE['login']]);
if ($datanew->role == "user") {
    echo "<h3>NOT A MANAGER </h3>";
    die;
}

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog : Homepage</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
     rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;1,600&display=swap"
     rel="stylesheet">
    <link rel="stylesheet" href="../../../public/assets/css/stylee.css">

</head>
<!-- admin panel -->

<body>
    <nav class="navbar">
        <img src="../../../public/assets/images/logo-res.png" class="logo" alt="" width="50px">
        <ul class="links-container">
            <li class="link-item"><a href="/login/logout" class="link">Logout</a></li>
            <li class="link-item"><a href="/index/home" class="link">Home</a></li>
            <li class="link-item"><a href="" class="link">Manager</a></li>
        </ul>
    </nav>

    <hr>
    <h1 class="text-center">Add Restaurant's Menu in this app</h1>
    <form action="/manager/addmenu" method="POST">
    <div class="form-group">
    <label for="exampleInputEmail1">Rid</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="rid" placeholder="Enter RESTRAUNT id">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Fid</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="fid" placeholder="Enter FOOD id">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Food Name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="fname"  placeholder="Enter food name">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Food cuisine type</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="type"  placeholder="Enter food type">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Food price</label>
    <input type="text" class="form-control"  name="fprice" placeholder="Enter food price">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Food details image</label>
    <input type="text" class="form-control"  name="img" placeholder="Enter image url">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Food ratings</label>
    <input type="text" class="form-control"  name="ratings" placeholder="Enter food ratings score">
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

    <hr>
    <h1 class="text-center">All Restaurants Food menu details</h1>

    <table class="table text-center" id='details'>
        <thead class="text-center   ">
            <tr>
                <th>FOOD-ID</th>
                <th>RESTAURANT-ID</th>
                <th>FOOD-NAME</th>
                <th>FOOD TYPE</th>
                <th>FOOD PRICE</th>
                <th>RATINGS</th>
                <th>ACTION</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $collection = $this->mongo->food;
            $data = $collection->find();


            foreach ($data as $value) {

                echo "<tr><td>" . $value->rid . "</td>";
                echo "<td>" . $value->fid . "</td>";
                echo "<td>" . $value->fname . "</td>";
                echo "<td>" . $value->type . "</td>";
                echo "<td>" . $value->fprice . "</td>";
                echo "<td>" . $value->ratings . "</td>";
                echo "<td><a href='/manager/editmenu?id=$value->fid' class='btn btn-info'>Edit</a>
                <a href='/manager/deletemenu?id=$value->fid' class='btn btn-danger'>Delete</a></td></tr>";
            }


            ?>
        </tbody>
    </table>
    </div>

    <hr>
    <h1 class="text-center">All Order details</h1>
    <table class="table text-center" id='details'>
        <thead class="text-center   ">
            <tr>
                <th>Food-ID</th>
                <th>Customer-NAME</th>
                <th>Restaurant name</th>
                <th>ADDRESS</th>
                <th>PRICE</th>
                <th>STATUS</th>
            </tr>
        </thead>
        <tbody>
        <tbody>
            <?php
          $collection = $this->mongo->order;
          $data = $collection->find();

            foreach ($data as $value) {

                echo "<tr><td>" . $value->fid . "</td>";
                echo "<td>" . $value->cname . "</td>";
                echo "<td>" . $value->rname . "</td>";
                echo "<td>" . $value->caddress . "</td>";
                echo "<td>" . $value->price . "</td>";
                echo "<td>" . $value->status . "</td></tr>";
            }


            ?>
        </tbody>
    </table>
    </div>
   
</body>
<script src="./jS/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
 integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
 integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>

</html>