
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Restaurant : Homepage</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css"
   integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
   integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;1,600&display=swap"
   rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
   integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="../../../public/assets/css/stylee.css">
</head>

<body>


  <?php
  echo "<nav class='navbar'>
          <img src='../assets/images/logo-res.png' class='logo' alt='' width='60px'>
          <ul class='links-container'>";
  if (isset($_COOKIE['login'])) {
    echo "<li class='link-item'><a href='/login/logout' class='link'>logout</a></li>";
    echo "<li class='link-item'><a href='/index/home' class='link'>Home</a></li>";
    echo "<li class='link-item'><a href='/order/vieworder' class='link'>My orders</a></li>";
    echo "<li class='link-item'><a href='/manager' class='link'>Manager</a></li>";
    echo "<li class='link-item'><a href='/admin/adminblog' class='link'>Admin</a></li>";
  } else {
    echo "<li class='link-item'><a href='/login/' class='link'>Login</a></li>";
    echo "<li class='link-item'><a href='/index/home' class='link'>Home</a></li>";
  }
  ?>

  </ul>
  </nav>

  <!-- slideshow -->
  <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="10000">
        <img src="../../../public/assets/images/tasty.jpg" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item" data-bs-interval="1000">
        <img src="../../../public/assets/images/header.png" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="../../../public/assets/images/tasty.jpg" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <br>
  <!-- end slideshow -->
  <!-- seach box -->
  <div class="container">

            <div class="row height d-flex justify-content-center align-items-center">
              <div class="col-md-6">
                <form action ="/index/search" method="POST">
                <div class="form">
                  <input type="text" name="search" class="form-control form-input"
                   placeholder="Search anything related to restraunt and cuisine...">
                  <input type="submit" value="search" class="form-control">
                </div>
                </form>
              </div>
            </div>
            
          </div>
  <!-- endsearch -->
  <!-- button to start writinh your own blog -->

  <!-- blog section -->
  <?php
  echo " <section class='blogs-section d-flex'>";
  foreach ($result as  $value) {
    
    echo "<div class='blog-card'>";
    echo "<img src='" . $value->img . "' class='blog-image' alt='' width='50%'/>";
    echo "<h1 class='blog-title'>Name:" . $value->rname . "</h1>";
    echo "<h3 class='blog-overview'>Address:" .$value->raddress . "</h3>";
    echo "<p class='blog-overview'>Ratings:" .$value->ratings . "/10</p>";
    echo "<a href='/index/fulldetail?id=" . $value->rid . "' class='btn btn-dark'>read</a>&nbsp&nbsp";
    echo "
    <i class='fa-solid fa-heart'>
    </i></a></div></br>";
  }
  echo "</section>";
  ?>
  </section>
  <?php

  if (isset($_COOKIE['login'])) {
    echo "
    <br>
    <br>
    <div class='text-center'>
  <button type='button' class='btn btn-secondary'><a href='/index/review' class='link'>Create Review</a></button>
</div>";
  }

  ?>
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
<script src="../assets/js/script.js"></script>
</html>