<section class="p-4 p-md-5 text-center text-lg-start shadow-1-strong rounded" style="
    background-image: url(https://mdbcdn.b-cdn.net/img/Photos/Others/background2.webp);
  ">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-body m-3">
                    <div class="row">
                        <div class="col-lg-4 d-flex justify-content-center align-items-center mb-4 mb-lg-0">
                            <img src="../../../public/assets/images/logo-res.png"
                             class="rounded-circle img-fluid shadow-1" alt="woman avatar" width="200" height="200" />
                        </div>
                        <div class="col-lg-8">
                            <form action ="/index/preview" method="POST">
                                <div class="form-group">
                                    <label for="exampleFormControlTextarea1"><h3>Write a Review!</h3></label>
                                    <textarea name="review" class="form-control"
                                     id="exampleFormControlTextarea1" rows="3"></textarea>
                                </div>
                                <input type="submit" value="POST!" class="btn btn-info">
                                <p class="fw-bold lead mb-2"><strong>Thank you!</strong></p>
                                <p class="fw-bold text-muted mb-0">App owner</p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>